use_frameworks!

platform :ios, '10.0'

target 'FLMultiSelectTableView_Example' do
  pod 'FLMultiSelectTableView', :path => '../'

  target 'FLMultiSelectTableView_Tests' do
    inherit! :search_paths

    
  end
end
